apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: pipeline-binding
  namespace: tekton-pipelines
spec:
  templatebindings:
    - templateref:
        name: pipeline-template
      params:
        - name: gitrevision
          value: $(event.head_commit.id)
        - name: gitrepositoryurl
          value: $(event.repository.url)
