/*
Copyright 2019 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/tektoncd/triggers/pkg/apis/triggers/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNamespacedInterceptors implements NamespacedInterceptorInterface
type FakeNamespacedInterceptors struct {
	Fake *FakeTriggersV1alpha1
}

var namespacedinterceptorsResource = schema.GroupVersionResource{Group: "triggers.tekton.dev", Version: "v1alpha1", Resource: "namespacedinterceptors"}

var namespacedinterceptorsKind = schema.GroupVersionKind{Group: "triggers.tekton.dev", Version: "v1alpha1", Kind: "NamespacedInterceptor"}

// Get takes name of the namespacedInterceptor, and returns the corresponding namespacedInterceptor object, and an error if there is any.
func (c *FakeNamespacedInterceptors) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.NamespacedInterceptor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(namespacedinterceptorsResource, name), &v1alpha1.NamespacedInterceptor{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NamespacedInterceptor), err
}

// List takes label and field selectors, and returns the list of NamespacedInterceptors that match those selectors.
func (c *FakeNamespacedInterceptors) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.NamespacedInterceptorList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(namespacedinterceptorsResource, namespacedinterceptorsKind, opts), &v1alpha1.NamespacedInterceptorList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.NamespacedInterceptorList{ListMeta: obj.(*v1alpha1.NamespacedInterceptorList).ListMeta}
	for _, item := range obj.(*v1alpha1.NamespacedInterceptorList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested namespacedInterceptors.
func (c *FakeNamespacedInterceptors) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(namespacedinterceptorsResource, opts))
}

// Create takes the representation of a namespacedInterceptor and creates it.  Returns the server's representation of the namespacedInterceptor, and an error, if there is any.
func (c *FakeNamespacedInterceptors) Create(ctx context.Context, namespacedInterceptor *v1alpha1.NamespacedInterceptor, opts v1.CreateOptions) (result *v1alpha1.NamespacedInterceptor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(namespacedinterceptorsResource, namespacedInterceptor), &v1alpha1.NamespacedInterceptor{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NamespacedInterceptor), err
}

// Update takes the representation of a namespacedInterceptor and updates it. Returns the server's representation of the namespacedInterceptor, and an error, if there is any.
func (c *FakeNamespacedInterceptors) Update(ctx context.Context, namespacedInterceptor *v1alpha1.NamespacedInterceptor, opts v1.UpdateOptions) (result *v1alpha1.NamespacedInterceptor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(namespacedinterceptorsResource, namespacedInterceptor), &v1alpha1.NamespacedInterceptor{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NamespacedInterceptor), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNamespacedInterceptors) UpdateStatus(ctx context.Context, namespacedInterceptor *v1alpha1.NamespacedInterceptor, opts v1.UpdateOptions) (*v1alpha1.NamespacedInterceptor, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(namespacedinterceptorsResource, "status", namespacedInterceptor), &v1alpha1.NamespacedInterceptor{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NamespacedInterceptor), err
}

// Delete takes name of the namespacedInterceptor and deletes it. Returns an error if one occurs.
func (c *FakeNamespacedInterceptors) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(namespacedinterceptorsResource, name, opts), &v1alpha1.NamespacedInterceptor{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNamespacedInterceptors) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(namespacedinterceptorsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.NamespacedInterceptorList{})
	return err
}

// Patch applies the patch and returns the patched namespacedInterceptor.
func (c *FakeNamespacedInterceptors) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NamespacedInterceptor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(namespacedinterceptorsResource, name, pt, data, subresources...), &v1alpha1.NamespacedInterceptor{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NamespacedInterceptor), err
}
