/*
Copyright 2019 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/tektoncd/triggers/pkg/apis/triggers/v1alpha1"
	triggersv1alpha1 "github.com/tektoncd/triggers/pkg/client/clientset/versioned/typed/triggers/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeScheduledTemplates implements ScheduledTemplateInterface
type fakeScheduledTemplates struct {
	*gentype.FakeClientWithList[*v1alpha1.ScheduledTemplate, *v1alpha1.ScheduledTemplateList]
	Fake *FakeTriggersV1alpha1
}

func newFakeScheduledTemplates(fake *FakeTriggersV1alpha1, namespace string) triggersv1alpha1.ScheduledTemplateInterface {
	return &fakeScheduledTemplates{
		gentype.NewFakeClientWithList[*v1alpha1.ScheduledTemplate, *v1alpha1.ScheduledTemplateList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("scheduledtemplates"),
			v1alpha1.SchemeGroupVersion.WithKind("ScheduledTemplate"),
			func() *v1alpha1.ScheduledTemplate { return &v1alpha1.ScheduledTemplate{} },
			func() *v1alpha1.ScheduledTemplateList { return &v1alpha1.ScheduledTemplateList{} },
			func(dst, src *v1alpha1.ScheduledTemplateList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ScheduledTemplateList) []*v1alpha1.ScheduledTemplate {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.ScheduledTemplateList, items []*v1alpha1.ScheduledTemplate) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
