/*
Copyright 2019 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/tektoncd/triggers/pkg/apis/triggers/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeScheduledTemplates implements ScheduledTemplateInterface
type FakeScheduledTemplates struct {
	Fake *FakeTriggersV1alpha1
	ns   string
}

var scheduledtemplatesResource = v1alpha1.SchemeGroupVersion.WithResource("scheduledtemplates")

var scheduledtemplatesKind = v1alpha1.SchemeGroupVersion.WithKind("ScheduledTemplate")

// Get takes name of the scheduledTemplate, and returns the corresponding scheduledTemplate object, and an error if there is any.
func (c *FakeScheduledTemplates) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ScheduledTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(scheduledtemplatesResource, c.ns, name), &v1alpha1.ScheduledTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ScheduledTemplate), err
}

// List takes label and field selectors, and returns the list of ScheduledTemplates that match those selectors.
func (c *FakeScheduledTemplates) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ScheduledTemplateList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(scheduledtemplatesResource, scheduledtemplatesKind, c.ns, opts), &v1alpha1.ScheduledTemplateList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ScheduledTemplateList{ListMeta: obj.(*v1alpha1.ScheduledTemplateList).ListMeta}
	for _, item := range obj.(*v1alpha1.ScheduledTemplateList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested scheduledTemplates.
func (c *FakeScheduledTemplates) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(scheduledtemplatesResource, c.ns, opts))

}

// Create takes the representation of a scheduledTemplate and creates it.  Returns the server's representation of the scheduledTemplate, and an error, if there is any.
func (c *FakeScheduledTemplates) Create(ctx context.Context, scheduledTemplate *v1alpha1.ScheduledTemplate, opts v1.CreateOptions) (result *v1alpha1.ScheduledTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(scheduledtemplatesResource, c.ns, scheduledTemplate), &v1alpha1.ScheduledTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ScheduledTemplate), err
}

// Update takes the representation of a scheduledTemplate and updates it. Returns the server's representation of the scheduledTemplate, and an error, if there is any.
func (c *FakeScheduledTemplates) Update(ctx context.Context, scheduledTemplate *v1alpha1.ScheduledTemplate, opts v1.UpdateOptions) (result *v1alpha1.ScheduledTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(scheduledtemplatesResource, c.ns, scheduledTemplate), &v1alpha1.ScheduledTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ScheduledTemplate), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeScheduledTemplates) UpdateStatus(ctx context.Context, scheduledTemplate *v1alpha1.ScheduledTemplate, opts v1.UpdateOptions) (*v1alpha1.ScheduledTemplate, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(scheduledtemplatesResource, "status", c.ns, scheduledTemplate), &v1alpha1.ScheduledTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ScheduledTemplate), err
}

// Delete takes name of the scheduledTemplate and deletes it. Returns an error if one occurs.
func (c *FakeScheduledTemplates) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(scheduledtemplatesResource, c.ns, name, opts), &v1alpha1.ScheduledTemplate{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeScheduledTemplates) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(scheduledtemplatesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ScheduledTemplateList{})
	return err
}

// Patch applies the patch and returns the patched scheduledTemplate.
func (c *FakeScheduledTemplates) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ScheduledTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(scheduledtemplatesResource, c.ns, name, pt, data, subresources...), &v1alpha1.ScheduledTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ScheduledTemplate), err
}
