version: "2"
run:
  build-tags:
    - e2e
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - depguard
    - dogsled
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    - forbidigo
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecksumtype
    - goconst
    - gocritic
    - goheader
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - grouper
    - importas
    - inamedparam
    - interfacebloat
    - intrange
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nilerr
    - nilnesserr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - perfsprint
    - promlinter
    - protogetter
    - reassign
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - tagalign
    - testableexamples
    - testifylint
    - thelper
    - unconvert
    - usestdlibvars
    - usetesting
    - whitespace
    - zerologlint
  disable:
    - cyclop
    - dupl
    - err113
    - exhaustruct
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocyclo
    - godot
    - godox
    - gomoddirectives
    - iface
    - ireturn
    - lll
    - mnd
    - nestif
    - nlreturn
    - nonamedreturns
    - paralleltest
    - prealloc
    - predeclared
    - recvcheck
    - revive
    - staticcheck
    - tagliatelle
    - testpackage
    - tparallel
    - unparam
    - varnamelen
    - wastedassign
    - wrapcheck
    - wsl
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gosec
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
      - vendor
      - pkg/client/clientset/(.*)/fake
      - pkg/client/injection
      - .*/zz_generated.deepcopy.go
      - pkg/apis/triggers/v1beta1/openapi_generated.go

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - vendor
      - vendor
      - pkg/client/clientset/(.*)/fake
      - pkg/client/injection
      - .*/zz_generated.deepcopy.go
      - pkg/apis/triggers/v1beta1/openapi_generated.go
