apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: run-triggers-publish-
spec:
  serviceAccount: release-right-meow
  taskRef:
    name: publish-tekton-triggers
  inputs:
    resources:
    - name: source
      resourceRef:
        name: tekton-triggers-git
    - name: bucket
      resourceRef:
        name: tekton-bucket
    params:
    - name: versionTag
      value: v0.11111.0 # REPLACE with the version you want to release, including `v`. For nightly releases, we might want to use `vYYYYMMDD-commit`
    - name: imageRegistry
      value: gcr.io/tekton-releases # REPLACE with your own registry
    - name: pathToProject
      value: github.com/tektoncd/triggers
  outputs:
    resources:
    - name: bucket
      resourceRef:
        name: tekton-bucket
    - name: builtControllerImage
      resourceRef:
        name: triggers-controller-image
    - name: builtWebhookImage
      resourceRef:
        name: triggers-webhook-image
    - name: builtEventListenerSinkImage
      resourceRef:
        name: event-listener-sink-image