apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: tekton-triggers-git # Replace with a new name e.g. tekton-triggers-git-v0-6-1
spec:
  type: git
  params:
  - name: url
    value: https://github.com/tektoncd/triggers
  - name: revision
    value: $REPLACE_ME # REPLACE with the commit you want to release
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: tekton-triggers-bucket
spec:
  type: storage
  params:
  - name: type
    value: gcs
  - name: location
    value: gs://tekton-releases/triggers
  - name: dir
    value: "y"
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: triggers-controller-image
spec:
  type: image
  params:
  - name: url
    value: cmd/controller  # Registry is provided via parameter, this is a hack see #569
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: triggers-webhook-image
spec:
  type: image
  params:
  - name: url
    value: cmd/webhook  # Registry is provided via parameter, this is a hack see #569
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: event-listener-sink-image
spec:
  type: image
  params:
  - name: url
    value: cmd/eventlistenersink  # Registry is provided via parameter, this is a hack see #569
# ---
# apiVersion: tekton.dev/v1alpha1
# kind: PipelineResource
# metadata:
#   name: post-release-trigger
# spec:
#   type: cloudEvent
#   params:
#   - name: targetURI
#     value: http://post-release-trigger-sink  # This has to be changed to a valid URL
