apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  token: dGVzdC1zZWNyZXQ=
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: cel-listener-interceptor-with-secret-comparison
spec:
  serviceAccountName: tekton-triggers-example-sa
  triggers:
    - name: cel-trig-with-matches
      interceptors:
        - cel:
            filter: "'test-secret'.compareSecret('token', 'mysecret')"
      bindings:
      - ref: pipeline-binding
      template:
        name: pipeline-template
