apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: cel-eventlistener-no-filter
spec:
  serviceAccountName: tekton-triggers-example-sa
  triggers:
    - name: cel-trig
      interceptors:
        - cel:
            overlays:
            - key: extensions.truncated_sha
              expression: "truncate(body.pull_request.head.sha, 7)"
      bindings:
      - name: pipeline-binding
      template:
        name: pipeline-template
