---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: listener-embed-binding
spec:
  serviceAccountName: tekton-triggers-example-sa
  triggers:
    - name: foo-trig
      bindings:
        - ref: pipeline-binding
        - name: message-binding
          spec:
            params:
              - name: message
                value: Hello from the Triggers EventListener(listener-embed-binding)!
      template:
        name: pipeline-template
