---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: listener-tolerations
spec:
  serviceAccountName: tekton-triggers-example-sa
  podTemplate:
    tolerations:
    - key: key
      value: value
      operator: Equal
      effect: NoSchedule
  triggers:
    - name: foo-trig
      bindings:
        - ref: pipeline-binding
        - ref: message-binding
      template:
        name: pipeline-template
