apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: listener
spec:
  serviceAccountName: tekton-triggers-example-sa
  triggers:
    - binding:
        name: pipeline-binding
        params:
          - name: message
            value: Hello from the Triggers EventListener!
      template:
        name: pipeline-template
