apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: listener
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-triggers-controller
  triggers:
    - binding:
        name: pipeline-binding
      template:
        name: pipeline-template
