apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: gitlab-listener-interceptor
spec:
  serviceAccountName: tekton-triggers-example-sa
  triggers:
    - name: foo-trig
      interceptor:
        gitlab:
          secretRef:
            secretName: foo
            secretKey: bar
            namespace: baz
          eventTypes:
          - Push Hook
      bindings:
      - name: pipeline-binding
      template:
        name: pipeline-template
