# This is a re-deceleration of the admin-role.yaml ClusterRoleBinding.
# It allows for:
# - admin-role.yaml, a symbolic link to /examples/rbac.yaml .
# - modified subject namespace of 'getting-started'.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-triggers-example-clusterbinding
subjects:
- kind: ServiceAccount
  name: tekton-triggers-example-sa
  namespace: getting-started
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-example-clusterrole