apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: cron-binding
spec:
  params:
  - name: gitrevision
    value: main
  - name: gitrepositoryurl
    value: https://github.com/tektoncd/triggers
  - name: contenttype
    value: $(header.Content-Type)
