---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: embedded-trigger-listener
spec:
  serviceAccountName: tekton-triggers-example-sa
  triggers:
    - name: foo-trig
      bindings:
        - ref: pipeline-binding
        - ref: message-binding
      template:
        ref: pipeline-template
