apiVersion: v1
kind: Service
metadata:
  labels:
    app: tekton-triggers-webhook
  name: tekton-triggers-webhook
  namespace: tekton-pipelines
spec:
  ports:
    - port: 443
      targetPort: 8443
  selector:
    app: tekton-triggers-webhook
