apiVersion: v1
kind: Service
metadata:
  labels:
    app: tekton-triggers-webhook
    version: "devel"
    triggers.tekton.dev/release: "devel"
  name: tekton-triggers-webhook
  namespace: tekton-pipelines
spec:
  ports:
    - name: https-webhook
      port: 443
      targetPort: 8443
  selector:
    app: tekton-triggers-webhook
