apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  token: dGVzdC1zZWNyZXQ=
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: cel-listener-interceptor-with-secret-comparison
spec:
  serviceAccountName: tekton-triggers-example-sa
  triggers:
    - name: cel-trig-with-matches
      interceptors:
      - ref:
          name: "cel"
        params:
        - name: "filter"
          value: "'test-secret'.compareSecret('token', 'mysecret')"
      bindings:
      - ref: pipeline-binding
      template:
        ref: pipeline-template
