name: Bump Deps

on:
  schedule:
  - cron: '0 6 * * 2' # weekly at 6AM Tuesday
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  bump-deps:
    name: Bump Deps

    # Don't bother bumping deps on forks.
    if: ${{ github.repository == 'tektoncd/cli' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - run: ./hack/update-deps.sh --upgrade
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        title: "Bump dependencies using hack/bump-deps.sh"
        commit-message: "Bump dependencies using hack/bump-deps.sh"
        labels: dependencies
        assignees: vdemeester
        delete-branch: true
