name: Triggers Integration

on: [workflow_call]

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  e2e-tests:
    concurrency:
      group: ${{ github.workflow }}-e2e-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    name: e2e tests
    runs-on: ubuntu-latest
    env:
      KO_DOCKER_REPO: registry.local:5000/tekton
      CLUSTER_DOMAIN: c${{ github.run_id }}.local
      ARTIFACTS: ${{ github.workspace }}/artifacts
      KOCACHE: /tmp/ko-cache

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: "go.mod"
      - name: Cache ko build cache
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306  # v5.0.3
        with:
          path: /tmp/ko-cache
          key: ${{ runner.os }}-${{ runner.arch }}-ko-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-ko-
      - uses: ko-build/setup-ko@d006021bd0c28d1ce33a07e7943d48b079944c8d # v0.9

      - name: Install Dependencies
        working-directory: ./
        run: |
          echo '::group:: install go-junit-report'
          go install github.com/jstemmer/go-junit-report@v0.9.1
          echo '::endgroup::'

          echo '::group::create required folders'
          mkdir -p "${ARTIFACTS}"
          echo '::endgroup::'

          echo "${GOPATH}/bin" >> "$GITHUB_PATH"

      - name: Run Integration tests
        run: |
          ./test/setup-kind.sh \
            --registry-url $(echo ${KO_DOCKER_REPO} | cut -d'/' -f 1) \
            --cluster-suffix c${{ github.run_id }}.local \
            --nodes 3 \
            --k8s-version v1.29.x \
            --e2e-script ./test/gh-e2e-tests.sh \
            --e2e-env ./test/e2e-tests-kind-prow.env

      - name: Upload test results
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        if: ${{ failure() }}
        with:
          path: ${{ env.ARTIFACTS }}
