name: Slash Command Routing

permissions:
  contents: read

on:
  issue_comment:
    types: [created]

jobs:
  check_comments:
    if: ${{ github.event.issue.pull_request }}
    permissions:
      issues: write # for peter-evans/slash-command-dispatch to create issue reaction
      pull-requests: write # for peter-evans/slash-command-dispatch to create PR reaction
    uses: tektoncd/plumbing/.github/workflows/_slash.yml@4b57443b85569e5bb7d9ee440bf5cae99cb642cb
    secrets: inherit
