/*
Copyright 2019 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/tektoncd/triggers/pkg/apis/triggers/v1alpha1"
	scheme "github.com/tektoncd/triggers/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// InterceptorTypesGetter has a method to return a InterceptorTypeInterface.
// A group's client should implement this interface.
type InterceptorTypesGetter interface {
	InterceptorTypes() InterceptorTypeInterface
}

// InterceptorTypeInterface has methods to work with InterceptorType resources.
type InterceptorTypeInterface interface {
	Create(ctx context.Context, interceptorType *v1alpha1.InterceptorType, opts v1.CreateOptions) (*v1alpha1.InterceptorType, error)
	Update(ctx context.Context, interceptorType *v1alpha1.InterceptorType, opts v1.UpdateOptions) (*v1alpha1.InterceptorType, error)
	UpdateStatus(ctx context.Context, interceptorType *v1alpha1.InterceptorType, opts v1.UpdateOptions) (*v1alpha1.InterceptorType, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.InterceptorType, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.InterceptorTypeList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.InterceptorType, err error)
	InterceptorTypeExpansion
}

// interceptorTypes implements InterceptorTypeInterface
type interceptorTypes struct {
	client rest.Interface
}

// newInterceptorTypes returns a InterceptorTypes
func newInterceptorTypes(c *TriggersV1alpha1Client) *interceptorTypes {
	return &interceptorTypes{
		client: c.RESTClient(),
	}
}

// Get takes name of the interceptorType, and returns the corresponding interceptorType object, and an error if there is any.
func (c *interceptorTypes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.InterceptorType, err error) {
	result = &v1alpha1.InterceptorType{}
	err = c.client.Get().
		Resource("interceptortypes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of InterceptorTypes that match those selectors.
func (c *interceptorTypes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.InterceptorTypeList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.InterceptorTypeList{}
	err = c.client.Get().
		Resource("interceptortypes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested interceptorTypes.
func (c *interceptorTypes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("interceptortypes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a interceptorType and creates it.  Returns the server's representation of the interceptorType, and an error, if there is any.
func (c *interceptorTypes) Create(ctx context.Context, interceptorType *v1alpha1.InterceptorType, opts v1.CreateOptions) (result *v1alpha1.InterceptorType, err error) {
	result = &v1alpha1.InterceptorType{}
	err = c.client.Post().
		Resource("interceptortypes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(interceptorType).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a interceptorType and updates it. Returns the server's representation of the interceptorType, and an error, if there is any.
func (c *interceptorTypes) Update(ctx context.Context, interceptorType *v1alpha1.InterceptorType, opts v1.UpdateOptions) (result *v1alpha1.InterceptorType, err error) {
	result = &v1alpha1.InterceptorType{}
	err = c.client.Put().
		Resource("interceptortypes").
		Name(interceptorType.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(interceptorType).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *interceptorTypes) UpdateStatus(ctx context.Context, interceptorType *v1alpha1.InterceptorType, opts v1.UpdateOptions) (result *v1alpha1.InterceptorType, err error) {
	result = &v1alpha1.InterceptorType{}
	err = c.client.Put().
		Resource("interceptortypes").
		Name(interceptorType.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(interceptorType).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the interceptorType and deletes it. Returns an error if one occurs.
func (c *interceptorTypes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("interceptortypes").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *interceptorTypes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("interceptortypes").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched interceptorType.
func (c *interceptorTypes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.InterceptorType, err error) {
	result = &v1alpha1.InterceptorType{}
	err = c.client.Patch(pt).
		Resource("interceptortypes").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
