/*
Copyright 2019 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	triggersv1alpha1 "github.com/tektoncd/triggers/pkg/apis/triggers/v1alpha1"
	scheme "github.com/tektoncd/triggers/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ScheduledTemplatesGetter has a method to return a ScheduledTemplateInterface.
// A group's client should implement this interface.
type ScheduledTemplatesGetter interface {
	ScheduledTemplates(namespace string) ScheduledTemplateInterface
}

// ScheduledTemplateInterface has methods to work with ScheduledTemplate resources.
type ScheduledTemplateInterface interface {
	Create(ctx context.Context, scheduledTemplate *triggersv1alpha1.ScheduledTemplate, opts v1.CreateOptions) (*triggersv1alpha1.ScheduledTemplate, error)
	Update(ctx context.Context, scheduledTemplate *triggersv1alpha1.ScheduledTemplate, opts v1.UpdateOptions) (*triggersv1alpha1.ScheduledTemplate, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, scheduledTemplate *triggersv1alpha1.ScheduledTemplate, opts v1.UpdateOptions) (*triggersv1alpha1.ScheduledTemplate, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*triggersv1alpha1.ScheduledTemplate, error)
	List(ctx context.Context, opts v1.ListOptions) (*triggersv1alpha1.ScheduledTemplateList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *triggersv1alpha1.ScheduledTemplate, err error)
	ScheduledTemplateExpansion
}

// scheduledTemplates implements ScheduledTemplateInterface
type scheduledTemplates struct {
	*gentype.ClientWithList[*triggersv1alpha1.ScheduledTemplate, *triggersv1alpha1.ScheduledTemplateList]
}

// newScheduledTemplates returns a ScheduledTemplates
func newScheduledTemplates(c *TriggersV1alpha1Client, namespace string) *scheduledTemplates {
	return &scheduledTemplates{
		gentype.NewClientWithList[*triggersv1alpha1.ScheduledTemplate, *triggersv1alpha1.ScheduledTemplateList](
			"scheduledtemplates",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *triggersv1alpha1.ScheduledTemplate { return &triggersv1alpha1.ScheduledTemplate{} },
			func() *triggersv1alpha1.ScheduledTemplateList { return &triggersv1alpha1.ScheduledTemplateList{} },
		),
	}
}
